/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './**/*.html'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        'on-primary-container': '#636565',
        'primary-container': '#e2e2e2',
        'secondary-fixed-dim': '#e9c349',
        'primary-fixed-dim': '#c6c6c7',
        'tertiary': '#ffffff',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131313',
        'inverse-on-surface': '#303030',
        'error-container': '#93000a',
        'on-error': '#690005',
        'surface-variant': '#353535',
        'surface': '#131313',
        'muted-gold': '#735C00',
        'secondary': '#e9c349',
        'outline-variant': '#444748',
        'surface-bright': '#393939',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#454747',
        'error': '#ffb4ab',
        'surface-container': '#1f1f1f',
        'secondary-container': '#af8d11',
        'on-primary-fixed': '#1a1c1c',
        'on-secondary-fixed': '#241a00',
        'primary': '#ffffff',
        'inverse-surface': '#e2e2e2',
        'tertiary-fixed': '#e2e2e2',
        'architectural-gray': '#1A1A1A',
        'on-primary': '#2f3131',
        'inverse-primary': '#5d5f5f',
        'deep-gold': '#C5A028',
        'on-secondary-container': '#342800',
        'tertiary-container': '#e2e2e2',
        'surface-container-low': '#1b1b1b',
        'on-tertiary-fixed-variant': '#454747',
        'secondary-fixed': '#ffe088',
        'background': '#000000',
        'on-background': '#e2e2e2',
        'surface-tint': '#c6c6c7',
        'on-secondary': '#3c2f00',
        'surface-container-highest': '#353535',
        'on-secondary-fixed-variant': '#574500',
        'surface-container-lowest': '#0e0e0e',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c4c7c8',
        'on-tertiary': '#2f3131',
        'outline': '#8e9192',
        'on-tertiary-container': '#636565',
        'blueprint-line': 'rgba(255, 255, 255, 0.05)',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'grid-line': '1px',
        'gutter': '24px',
        'unit': '8px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Montserrat', 'system-ui', 'sans-serif'],
        'headline-xl': ['Montserrat', 'system-ui', 'sans-serif'],
        'headline-lg': ['Montserrat', 'system-ui', 'sans-serif'],
        'label-technical': ['"JetBrains Mono"', 'monospace'],
        'body-lg': ['Montserrat', 'system-ui', 'sans-serif'],
        'headline-md': ['Montserrat', 'system-ui', 'sans-serif'],
        'body-md': ['Montserrat', 'system-ui', 'sans-serif'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl':        ['80px', { lineHeight: '88px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-technical':    ['12px', { lineHeight: '16px', letterSpacing: '0.1em',  fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md':        ['24px', { lineHeight: '32px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm':           ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
